import type { Item } from "./types";
import { normaliseItem } from "./augments";

// Item type extended with description for lore
// Add `description?: string` to the Item interface in types.ts

const BASE_ITEMS: Item[] = [
// --
// COMMON
// --
{
id: "kz_br_c_01",
name: "[KIZUNA] MIL-Stub (Civic Profile)",
description: "Standard-issue neural compliance chip. Monitors thought-patterns for continuity deviation. Most workers never know it's there.",
rarity: "common",
type: "augmentation",
slot: "brain",
attackBonus: 2,
defenseBonus: 1,
hpBonus: 5,
icon: "🧠",
passiveEffect: 'kizuna_coldstart',
},
{
id: "tx_lu_c_01",
name: "[TIANXIA] Workforce Lung Liner",
description: "Mandatory fitment for port workers in the Pearl River delta. Filters particulates. Does not filter the smell.",
rarity: "common",
type: "augmentation",
slot: "lungs",
attackBonus: 1,
defenseBonus: 1,
hpBonus: 10,
icon: "🫁",
},
{
id: "hx_ms_c_01",
name: "[HELIX] Uptime Coupler (Basic)",
description: "Keeps the body clock synchronised to shift rotation. Workers with this installed sleep when Helix permits.",
rarity: "common",
type: "augmentation",
slot: "misc",
attackBonus: 2,
defenseBonus: 2,
hpBonus: 5,
structuralDefenseBonus: 1,
icon: "⚙️",
},
{
id: "cr_ey_c_01",
name: "[CROWN] Sun-Filter (Clinic Surplus)",
description: "Redistributed from decommissioned clinic stock. Reduces UV load near coastal extraction sites. The previous owner's prescription is still active.",
rarity: "common",
type: "augmentation",
slot: "eyes",
attackBonus: 3,
defenseBonus: 0,
hpBonus: 2,
icon: "👁️",
},
{
id: "pr_cn_c_01",
name: "[PARSU] Filter-Media Brick",
description: "Compressed bronchial paste. Administered nasally. Tastes like the inside of a recycling plant. Works.",
rarity: "common",
type: "consumable",
hpBonus: 20,
icon: "😷",
},
{
id: "io_er_c_01",
name: "[IOA] Dock-Worker Ear Plugs",
description: "Subdermal. Attenuates industrial noise above 85dB. A secondary function filters certain broadcast frequencies - this is not mentioned in the manual.",
rarity: "common",
type: "augmentation",
slot: "ears",
attackBonus: 1,
defenseBonus: 2,
hpBonus: 3,
icon: "👂",
},
{
id: "vk_la_c_01",
name: "[VOLKOV] Grip-Assist Sleeve (L)",
description: "Exoskeletal forearm cuff. Rated for cargo loading. The leftover tension from eight-hour shifts doesn't fully release when you take it off.",
rarity: "common",
type: "augmentation",
slot: "left_arm",
attackBonus: 4,
defenseBonus: 0,
hpBonus: 0,
structuralAttackBonus: 1,
icon: "🦾",
},
{
id: "vk_ra_c_01",
name: "[VOLKOV] Grip-Assist Sleeve (R)",
description: "Matching right-hand unit. Volkov sells them separately. Most buyers only ever afford one.",
rarity: "common",
type: "augmentation",
slot: "right_arm",
attackBonus: 4,
defenseBonus: 0,
hpBonus: 0,
structuralAttackBonus: 1,
icon: "🦾",
},
{
id: "hx_ll_c_01",
name: "[HELIX] Balance Calibrator (L)",
description: "Ankle joint stabiliser for uneven terrain. Standard issue on Helix platforms. The magnets in the heel orient you toward the nearest emergency exit.",
rarity: "common",
type: "augmentation",
slot: "left_leg",
attackBonus: 1,
defenseBonus: 2,
hpBonus: 5,
structuralDefenseBonus: 1,
icon: "🦿",
},
{
id: "hx_rl_c_01",
name: "[HELIX] Balance Calibrator (R)",
description: "The right-side unit. Helix workers call the pair 'the leash.' The joke is not entirely a joke.",
rarity: "common",
type: "augmentation",
slot: "right_leg",
attackBonus: 1,
defenseBonus: 2,
hpBonus: 5,
structuralDefenseBonus: 1,
icon: "🦿",
},
{
id: "io_nz_c_01",
name: "[IOA] Basic Air Filter",
description: "Nasal implant. Filters sulphur compounds and heavy particulates. Approved for use in IOA managed port zones. Does not filter the grief.",
rarity: "common",
type: "augmentation",
slot: "nose",
attackBonus: 0,
defenseBonus: 1,
hpBonus: 8,
icon: "👃",
},

// --
// UNCOMMON
// --
{
id: "kz_br_u_01",
name: "[KIZUNA] Compliance Kernel (Shift-Safe)",
description: "Enhanced version of the civic stub. Logs emotional spikes and reports them to HR. The employee agreement covers this. You agreed.",
rarity: "uncommon",
type: "augmentation",
slot: "brain",
attackBonus: 4,
defenseBonus: 2,
hpBonus: 10,
icon: "🧠",
passiveEffect: 'kizuna_coldstart',
},
{
id: "tx_er_u_01",
name: "[TIANXIA] Whisper-Band Ears",
description: "Tunes into the 2.4GHz administrative band used by Tianxia compliance officers. Lets you hear when the inspectors are coming.",
rarity: "uncommon",
type: "augmentation",
slot: "ears",
attackBonus: 2,
defenseBonus: 4,
hpBonus: 6,
icon: "👂",
},
{
id: "io_nz_u_01",
name: "[IOA] Salt-Air Nose Gate",
description: "Designed for coastal salvage divers. Seals the nasal cavity against seawater ingress. The previous owner worked the plastic gyre. The serial number has been filed off.",
rarity: "uncommon",
type: "augmentation",
slot: "nose",
attackBonus: 0,
defenseBonus: 2,
hpBonus: 16,
icon: "👃",
},
{
id: "hx_ll_u_01",
name: "[HELIX] Heat-Step Calibrator (L)",
description: "Thermal insulation in the sole. Rated for platform decks running at 60°C. Standard fitment for workers near the exhaust stacks.",
rarity: "uncommon",
type: "augmentation",
slot: "left_leg",
attackBonus: 2,
defenseBonus: 4,
hpBonus: 10,
structuralDefenseBonus: 2,
icon: "🦿",
},
{
id: "pr_hy_u_01",
name: "[PARSU] Electrolyte Salt-Bar",
description: "Dissolvable bronchial plug. Floods the bloodstream with sodium and trace minerals. Used by long-haul divers and people who have given up on sleeping.",
rarity: "uncommon",
type: "consumable",
hpBonus: 50,
icon: "🧂",
},
{
id: "cr_ey_u_01",
name: "[CROWN] Low-Light Optic Filter",
description: "Retinal overlay for sub-lux environments. Originally designed for Crown's underwater survey teams. The colour calibration assumes the sky is always grey.",
rarity: "uncommon",
type: "augmentation",
slot: "eyes",
attackBonus: 6,
defenseBonus: 0,
hpBonus: 4,
icon: "👁️",
},
{
id: "vk_la_u_01",
name: "[VOLKOV] Impact Arm Brace (L)",
description: "Hydraulic impact buffer. Absorbs recoil from heavy tooling. Also absorbs the feeling in your elbow after about six months.",
rarity: "uncommon",
type: "augmentation",
slot: "left_arm",
attackBonus: 8,
defenseBonus: 0,
hpBonus: 0,
structuralAttackBonus: 3,
icon: "🦾",
},
{
id: "vk_ra_u_01",
name: "[VOLKOV] Impact Arm Brace (R)",
description: "Right-hand version. The bracing on this one is tighter than the left. Volkov's tolerances are inconsistent. This is a feature.",
rarity: "uncommon",
type: "augmentation",
slot: "right_arm",
attackBonus: 8,
defenseBonus: 0,
hpBonus: 0,
structuralAttackBonus: 3,
icon: "🦾",
},
{
id: "hx_rl_u_01",
name: "[HELIX] Heat-Step Calibrator (R)",
description: "Paired right-side unit. The left and right calibrators communicate. If one fails, the other locks. Helix calls this a safety feature.",
rarity: "uncommon",
type: "augmentation",
slot: "right_leg",
attackBonus: 2,
defenseBonus: 4,
hpBonus: 10,
structuralDefenseBonus: 2,
icon: "🦿",
},
{
id: "tx_lu_u_01",
name: "[TIANXIA] Smog-Filter Lung Pack",
description: "Second-generation lung liner. Approved for use in Tier 2 pollution zones. The waiting list is eighteen months. Some people don't wait.",
rarity: "uncommon",
type: "augmentation",
slot: "lungs",
attackBonus: 2,
defenseBonus: 2,
hpBonus: 20,
icon: "🫁",
},
{
id: "hx_ms_u_01",
name: "[HELIX] Uptime Coupler (Enhanced)",
description: "Upgrades the sleep suppression from 6-hour windows to 4-hour windows. Helix productivity reports show a 34% increase in output. The other reports are not public.",
rarity: "uncommon",
type: "augmentation",
slot: "misc",
attackBonus: 4,
defenseBonus: 4,
hpBonus: 10,
structuralDefenseBonus: 2,
icon: "⚙️",
},

// --
// RARE
// --
{
id: "cr_ey_r_01",
name: "[CROWN] Ocular Profile: Glare-Cut",
description: "Polarised retinal filter used by Crown survey teams operating on open water. Removes surface glare entirely. Also removes the warmth from sunlight. Users report this is unsettling.",
rarity: "rare",
type: "augmentation",
slot: "eyes",
attackBonus: 9,
defenseBonus: 0,
hpBonus: 6,
icon: "👁️",
},
{
id: "vk_ra_r_01",
name: "[VOLKOV] Strike Arm Rig (R)",
description: "Combat-rated hydraulic arm. Originally manufactured for private security contractors. This unit has been reissued twice. There is no record of the previous owners.",
rarity: "rare",
type: "augmentation",
slot: "right_arm",
attackBonus: 12,
defenseBonus: 0,
hpBonus: 0,
structuralAttackBonus: 4,
icon: "🦾",
},
{
id: "tx_lu_r_01",
name: "[TIANXIA] Smoke-Season Lungs (V2)",
description: "Designed for the annual fire-season in the agricultural zones. Extended filtration, active carbon lining. The V1 had a recall. This is not discussed.",
rarity: "rare",
type: "augmentation",
slot: "lungs",
attackBonus: 3,
defenseBonus: 3,
hpBonus: 30,
icon: "🫁",
},
{
id: "hx_ms_r_01",
name: "[HELIX] Service-Node Handshake",
description: "Subdermal data port. Allows direct connection to Helix infrastructure. The handshake is one-way. Helix reads from you. You do not read from Helix.",
rarity: "rare",
type: "augmentation",
slot: "misc",
attackBonus: 6,
defenseBonus: 6,
hpBonus: 15,
structuralDefenseBonus: 3,
evasionBonus: 2,
icon: "⚙️",
},
{
id: "io_in_r_01",
name: "[IOA] Dock-Breather Inhaler",
description: "Emergency bronchial clearance. Rated for chemical exposure events. The taste lingers for three days. Dock workers consider this a good sign - it means the lungs are still there.",
rarity: "rare",
type: "consumable",
hpBonus: 100,
icon: "💉",
},
{
id: "kz_br_r_01",
name: "[KIZUNA] Shift-Manager Kernel",
description: "Mid-level compliance implant. Grants the user limited access to workforce scheduling data - their own. The manager version grants access to everyone else's.",
rarity: "rare",
type: "augmentation",
slot: "brain",
attackBonus: 6,
defenseBonus: 3,
hpBonus: 15,
icon: "🧠",
passiveEffect: 'kizuna_coldstart',
},
{
id: "vk_la_r_01",
name: "[VOLKOV] Strike Arm Rig (L)",
description: "Left-hand unit. The grip calibration is set slightly too tight from factory. Every Volkov technician knows this. None of them have filed a correction.",
rarity: "rare",
type: "augmentation",
slot: "left_arm",
attackBonus: 12,
defenseBonus: 0,
hpBonus: 0,
structuralAttackBonus: 4,
icon: "🦾",
},
{
id: "tx_er_r_01",
name: "[TIANXIA] Threat-Ping Ears",
description: "Detects stress hormones in nearby individuals and converts them to a low audio tone. Useful for reading a room. The tone is constant in cities.",
rarity: "rare",
type: "augmentation",
slot: "ears",
attackBonus: 3,
defenseBonus: 6,
hpBonus: 9,
icon: "👂",
},
{
id: "io_nz_r_01",
name: "[IOA] Chem-Sense Nose Array",
description: "Chemoreceptor array. Identifies 400 distinct compounds by scent. Originally used for contamination detection. The sense of smell it provides is not quite human.",
rarity: "rare",
type: "augmentation",
slot: "nose",
attackBonus: 0,
defenseBonus: 3,
hpBonus: 24,
icon: "👃",
},
{
id: "hx_ll_r_01",
name: "[HELIX] Sprint-Boost Actuator (L)",
description: "Pneumatic assist for rapid response personnel. The actuator fires 80ms before the user consciously decides to run. Helix considers this an improvement.",
rarity: "rare",
type: "augmentation",
slot: "left_leg",
attackBonus: 3,
defenseBonus: 6,
hpBonus: 15,
structuralDefenseBonus: 3,
evasionBonus: 2,
icon: "🦿",
},
{
id: "hx_rl_r_01",
name: "[HELIX] Sprint-Boost Actuator (R)",
description: "Right-side actuator. The left fires first. For the 80 milliseconds between them, the body is committed to a direction the mind hasn't chosen yet.",
rarity: "rare",
type: "augmentation",
slot: "right_leg",
attackBonus: 3,
defenseBonus: 6,
hpBonus: 15,
structuralDefenseBonus: 3,
evasionBonus: 2,
icon: "🦿",
},

// --
// EPIC
// --
{
id: "vk_br_e_01",
name: "[VOLKOV] Operator Override (Hot Zone)",
description: "Military-grade neural suppression chip. Suppresses pain signalling and fear response in combat scenarios. Volkov's field trials were not voluntary.",
rarity: "epic",
type: "augmentation",
slot: "brain",
attackBonus: 10,
defenseBonus: 5,
hpBonus: 25,
structuralAttackBonus: 4,
icon: "🧠",
},
{
id: "cr_nz_e_01",
name: "[CROWN] Toxin Gate Nose Implant",
description: "Blocks absorption of 94 classified chemical agents through nasal tissue. Crown's roster of classified agents is longer than any government list.",
rarity: "epic",
type: "augmentation",
slot: "nose",
attackBonus: 0,
defenseBonus: 5,
hpBonus: 40,
icon: "👃",
},
{
id: "kz_ms_e_01",
name: "[KIZUNA] Certified Stack Spine (Audit-Grade)",
description: "Full spinal data relay. Every nerve signal logged, timestamped, transmitted. Used for high-clearance employees where Kizuna needs to know not just what you did, but what you felt while doing it.",
rarity: "epic",
type: "augmentation",
slot: "misc",
attackBonus: 10,
defenseBonus: 10,
hpBonus: 25,
icon: "📎",
passiveEffect: 'kizuna_coldstart',
},
{
id: "tx_la_e_01",
name: "[TIANXIA] Industrial Arm Actuator (L)",
description: "Heavy industrial prosthetic. The grip can crush steel plate. Used in deep-water extraction rigs. This one has scratches on the palm that don't match any tool profile.",
rarity: "epic",
type: "augmentation",
slot: "left_arm",
attackBonus: 20,
defenseBonus: 0,
hpBonus: 0,
icon: "🦾",
},
{
id: "pr_rx_e_01",
name: "[PARSU] Emergency Rehydrate Kit",
description: "Full-system electrolyte flood. Designed for heat collapse in restricted zones. The injection site bruises for a week. Nobody who needed this has ever complained about the bruise.",
rarity: "epic",
type: "consumable",
hpBonus: 200,
icon: "🧂",
},
{
id: "tx_ra_e_01",
name: "[TIANXIA] Industrial Arm Actuator (R)",
description: "The right-side unit. Tianxia marks the dominant arm with a red stripe during fitment. This one has a red stripe but the previous owner was left-handed.",
rarity: "epic",
type: "augmentation",
slot: "right_arm",
attackBonus: 20,
defenseBonus: 0,
hpBonus: 0,
icon: "🦾",
},
{
id: "cr_ey_e_01",
name: "[CROWN] Tactical Overlay Optics",
description: "Projects a threat assessment grid over the visual field. Highlights movement, heat signatures, structural weaknesses. The overlay cannot be fully disabled. Crown says this is intentional.",
rarity: "epic",
type: "augmentation",
slot: "eyes",
attackBonus: 15,
defenseBonus: 0,
hpBonus: 10,
icon: "👁️",
},
{
id: "vk_er_e_01",
name: "[VOLKOV] Threat-Vector Ears",
description: "Directional sound triangulation. Calculates the origin point of any sound within 200 metres. Users report hearing things they cannot locate. Volkov classifies these as calibration artefacts.",
rarity: "epic",
type: "augmentation",
slot: "ears",
attackBonus: 5,
defenseBonus: 10,
hpBonus: 15,
structuralAttackBonus: 2,
icon: "👂",
},
{
id: "tx_lu_e_01",
name: "[TIANXIA] Pressure-Seal Lungs",
description: "Rated to 400m depth. Used by Tianxia's deep-sea mineral extraction teams. The seal is total. When submerged, the user does not breathe. The user does not need to breathe. The user is aware of this.",
rarity: "epic",
type: "augmentation",
slot: "lungs",
attackBonus: 5,
defenseBonus: 5,
hpBonus: 50,
icon: "🫁",
},
{
id: "hx_ll_e_01",
name: "[HELIX] Combat Locomotion Frame (L)",
description: "Full leg replacement from the knee down. Designed for boarding operations on Helix extraction platforms. The stance it defaults to is the stance of someone who expects to fight.",
rarity: "epic",
type: "augmentation",
slot: "left_leg",
attackBonus: 5,
defenseBonus: 10,
hpBonus: 25,
structuralDefenseBonus: 5,
evasionBonus: 4,
icon: "🦿",
},
{
id: "hx_rl_e_01",
name: "[HELIX] Combat Locomotion Frame (R)",
description: "Right-side frame. When both units are installed, the gait is not quite human. Helix security teams are trained to recognise this walk from 50 metres.",
rarity: "epic",
type: "augmentation",
slot: "right_leg",
attackBonus: 5,
defenseBonus: 10,
hpBonus: 25,
structuralDefenseBonus: 5,
evasionBonus: 4,
icon: "🦿",
},

// --
// LEGENDARY
// --
{
id: "vk_lu_l_01",
name: "[VOLKOV] Smoke-Run Protocol (Limiter-Bent)",
description: "Black-market modification to standard lung hardware. Removes the oxygen-consumption ceiling. The body can now sustain output that should kill it. The limiter existed for a reason. Nobody who bent it has been available to explain why.",
rarity: "legendary",
type: "augmentation",
slot: "lungs",
attackBonus: 8,
defenseBonus: 8,
hpBonus: 80,
structuralAttackBonus: 3,
icon: "🫁",
},
{
id: "cr_ey_l_01",
name: "[CROWN] Ocular Profile: Night-Clean",
description: "Prototype night-vision array. Renders darkness as daylight. The colours are wrong - slightly too saturated, slightly too still. Users stop noticing after three weeks. Crown considers this acceptable.",
rarity: "legendary",
type: "augmentation",
slot: "eyes",
attackBonus: 24,
defenseBonus: 0,
hpBonus: 16,
icon: "🌙",
},
{
id: "kz_br_l_01",
name: "[KIZUNA] Sovereign Key (Prime Profile)",
description: "Top-tier neural administrative implant. Grants the user the ability to override lower-tier Kizuna implants in nearby individuals. The list of individuals with Prime Profile access is not published. It is very short.",
rarity: "legendary",
type: "augmentation",
slot: "brain",
attackBonus: 16,
defenseBonus: 8,
hpBonus: 40,
icon: "🧠",
passiveEffect: 'kizuna_coldstart',
},
{
id: "px_ms_l_01",
name: "[PATCHWORK] Ghost-Glass Fork (Offline UI)",
description: "Unregistered spinal relay. No manufacturer mark. No serial number. The interface it provides does not match any documented system. Someone built this to access something that should not be accessible. It still works.",
rarity: "legendary",
type: "augmentation",
slot: "misc",
attackBonus: 16,
defenseBonus: 16,
hpBonus: 40,
icon: "🏴‍☠️",
},
{
id: "io_st_l_01",
name: "[IOA] Black Broncho-Snap",
description: "Classified emergency respiratory override. Not available through standard IOA channels. The compound it releases is not in any public pharmacological database. It works in under four seconds. Nobody asks what it costs, later.",
rarity: "legendary",
type: "consumable",
hpBonus: 500,
icon: "💉",
},
{
id: "vk_la_l_01",
name: "[VOLKOV] Enforcer Arm (Black Market L)",
description: "Full left-arm combat replacement. Stripped from a decommissioned private military unit. The serial numbers map to a contractor that officially no longer exists. The arm still remembers what it was built for.",
rarity: "legendary",
type: "augmentation",
slot: "left_arm",
attackBonus: 32,
defenseBonus: 0,
hpBonus: 0,
structuralAttackBonus: 12,
icon: "🦾",
},
{
id: "vk_ra_l_01",
name: "[VOLKOV] Enforcer Arm (Black Market R)",
description: "Right-side unit. Found separately from the left. Someone removed these deliberately and distributed them apart. The reason is not recorded. Both units function as intended.",
rarity: "legendary",
type: "augmentation",
slot: "right_arm",
attackBonus: 32,
defenseBonus: 0,
hpBonus: 0,
structuralAttackBonus: 12,
icon: "🦾",
},
{
id: "px_er_l_01",
name: "[PATCHWORK] Ghost-Freq Ears (Unregistered)",
description: "Receives signals on frequencies that no registered device transmits on. The signals are there. They have always been there. Something is broadcasting on these frequencies continuously. The content is not language - not exactly.",
rarity: "legendary",
type: "augmentation",
slot: "ears",
attackBonus: 8,
defenseBonus: 16,
hpBonus: 24,
icon: "👂",
},
{
id: "px_nz_l_01",
name: "[PATCHWORK] Chem-Sniffer (Contraband Grade)",
description: "Detects 2,000+ compounds including several that are not supposed to exist outside controlled laboratory environments. The previous owner found something with this. The previous owner is not findable.",
rarity: "legendary",
type: "augmentation",
slot: "nose",
attackBonus: 0,
defenseBonus: 8,
hpBonus: 64,
icon: "👃",
},
{
id: "px_ll_l_01",
name: "[PATCHWORK] Exo-Sprint Frame (L)",
description: "Full-leg exoskeletal replacement. Salvage-built from at least four different manufacturer components. They should not be compatible. They work anyway. The gait it produces has been logged in surveillance footage from three different cities.",
rarity: "legendary",
type: "augmentation",
slot: "left_leg",
attackBonus: 8,
defenseBonus: 16,
hpBonus: 40,
icon: "🦿",
},
{
id: "px_rl_l_01",
name: "[PATCHWORK] Exo-Sprint Frame (R)",
description: "The right-side frame. The left and right were found on the same body. The body had other modifications that are not catalogued here. Some things are better left unexamined.",
rarity: "legendary",
type: "augmentation",
slot: "right_leg",
attackBonus: 8,
defenseBonus: 16,
hpBonus: 40,
icon: "🦿",
},

// ----------
// PATCHWORK TYPE A - SALVAGED CORPORATE
// Condition baked into name. Stats reflect
// original corp character, reduced by wear.
// ----------

// ── COMMON (CORRODED / WORN) ──────────────

{
id: "pw_a_vk_la_c_01",
name: "[PATCHWORK] Volkov Grip-Sleeve (L) - CORRODED",
description: "A Volkov exo-sleeve stripped from a downed operator. The hydraulic line is cracked, repaired with fishing line. Still bites.",
rarity: "common",
type: "augmentation",
slot: "left_arm",
attackBonus: 1,
defenseBonus: 0,
hpBonus: 0,
condition: "corroded",
icon: "🦾",
},
{
id: "pw_a_vk_ra_c_01",
name: "[PATCHWORK] Volkov Grip-Sleeve (R) - CORRODED",
description: "Right-side unit. The grip calibration drifts. Sometimes it locks. Most of the time it doesn't.",
rarity: "common",
type: "augmentation",
slot: "right_arm",
attackBonus: 1,
defenseBonus: 0,
hpBonus: 0,
condition: "corroded",
icon: "🦾",
},
{
id: "pw_a_tx_lu_c_01",
name: "[PATCHWORK] Tianxia Lung Liner - WORN",
description: "Factory-line respiratory mod, third owner minimum. The filter media is saturated. Breathes better than nothing.",
rarity: "common",
type: "augmentation",
slot: "lungs",
attackBonus: 0,
defenseBonus: 0,
hpBonus: 6,
condition: "worn",
icon: "🫁",
},
{
id: "pw_a_hx_ll_c_01",
name: "[PATCHWORK] Helix Balance Calibrator (L) - WORN",
description: "Ankle stabiliser still holding alignment. The heel magnet is demagnetised. Doesn't point anywhere anymore.",
rarity: "common",
type: "augmentation",
slot: "left_leg",
attackBonus: 0,
defenseBonus: 1,
hpBonus: 3,
condition: "worn",
icon: "🦿",
},
{
id: "pw_a_hx_rl_c_01",
name: "[PATCHWORK] Helix Balance Calibrator (R) - WORN",
description: "Right side. The leash, they called the pair. Only one half left. Still grips.",
rarity: "common",
type: "augmentation",
slot: "right_leg",
attackBonus: 0,
defenseBonus: 1,
hpBonus: 3,
condition: "worn",
icon: "🦿",
},
{
id: "pw_a_tx_la_c_01",
name: "[PATCHWORK] Tianxia Labour Arm (L) - CORRODED",
description: "Industrial prosthetic stripped from a dockworker's corpse. Salt-eaten at the elbow joint. Still hauls.",
rarity: "common",
type: "augmentation",
slot: "left_arm",
attackBonus: 2,
defenseBonus: 0,
hpBonus: 0,
condition: "corroded",
icon: "🦾",
},
{
id: "pw_a_io_er_c_01",
name: "[PATCHWORK] IOA Ear Plugs - DEGRADED",
description: "Subdermal audio filter, contacts corroded. Filters about half of what it used to. Still blocks the worst of it.",
rarity: "common",
type: "augmentation",
slot: "ears",
attackBonus: 0,
defenseBonus: 1,
hpBonus: 1,
condition: "degraded",
icon: "👂",
},
{
id: "pw_a_hx_ms_c_01",
name: "[PATCHWORK] Helix Uptime Coupler - CORRODED",
description: "Shift-sync implant, power cell replaced with a salvaged capacitor. Keeps you running. The dreams are wrong.",
rarity: "common",
type: "augmentation",
slot: "misc",
attackBonus: 1,
defenseBonus: 1,
hpBonus: 2,
condition: "corroded",
icon: "⚙️",
},

// ── UNCOMMON (WORN / DEGRADED) ────────────

{
id: "pw_a_vk_la_u_01",
name: "[PATCHWORK] Volkov Impact Brace (L) - WORN",
description: "Hydraulic buffer, still functional. Recoil absorption is down to maybe 60%. Enough.",
rarity: "uncommon",
type: "augmentation",
slot: "left_arm",
attackBonus: 4,
defenseBonus: 0,
hpBonus: 0,
condition: "worn",
icon: "🦾",
},
{
id: "pw_a_vk_ra_u_01",
name: "[PATCHWORK] Volkov Impact Brace (R) - WORN",
description: "Right side. The Volkov tolerance variance is still there - this one grips tighter than the left. Still a feature.",
rarity: "uncommon",
type: "augmentation",
slot: "right_arm",
attackBonus: 4,
defenseBonus: 0,
hpBonus: 0,
condition: "worn",
icon: "🦾",
},
{
id: "pw_a_cr_ey_u_01",
name: "[PATCHWORK] Crown Low-Light Filter - DEGRADED",
description: "Retinal overlay from a Crown survey kit. The colour calibration is gone. Everything is the same grey. Vision still works.",
rarity: "uncommon",
type: "augmentation",
slot: "eyes",
attackBonus: 3,
defenseBonus: 0,
hpBonus: 2,
condition: "degraded",
icon: "👁️",
},
{
id: "pw_a_tx_lu_u_01",
name: "[PATCHWORK] Tianxia Smog-Filter Pack - WORN",
description: "Second-generation liner, third owner. The active carbon is partially spent. Still better than raw air out here.",
rarity: "uncommon",
type: "augmentation",
slot: "lungs",
attackBonus: 1,
defenseBonus: 1,
hpBonus: 10,
condition: "worn",
icon: "🫁",
},
{
id: "pw_a_hx_ll_u_01",
name: "[PATCHWORK] Helix Heat-Step Calibrator (L) - WORN",
description: "Thermal sole insulation, still rated for moderate heat. The left-right comm link is dead. Doesn't matter.",
rarity: "uncommon",
type: "augmentation",
slot: "left_leg",
attackBonus: 1,
defenseBonus: 2,
hpBonus: 5,
condition: "worn",
icon: "🦿",
},
{
id: "pw_a_kz_br_u_01",
name: "[PATCHWORK] Kizuna Compliance Kernel - DEGRADED",
description: "Mid-tier neural chip, jailbroken and reinstalled. The HR reporting function was the first thing they stripped out. Cold on startup. Very cold.",
rarity: "uncommon",
type: "augmentation",
slot: "brain",
attackBonus: 2,
defenseBonus: 1,
hpBonus: 4,
condition: "degraded",
icon: "🧠",
},
{
id: "pw_a_vk_br_u_01",
name: "[PATCHWORK] Volkov Operator Override - DEGRADED",
description: "Pain suppression chip stripped from a decommissioned Volkov contractor. The fear response suppression still fires. The pain suppression is inconsistent.",
rarity: "uncommon",
type: "augmentation",
slot: "brain",
attackBonus: 4,
defenseBonus: 1,
hpBonus: 8,
condition: "degraded",
icon: "🧠",
},

// ── RARE (WORN / PRISTINE) ────────────────

{
id: "pw_a_vk_ra_r_01",
name: "[PATCHWORK] Volkov Strike Rig (R) - WORN",
description: "Combat-rated hydraulic arm, reissued again. Previous owners not recorded. The grip memory is someone else's.",
rarity: "rare",
type: "augmentation",
slot: "right_arm",
attackBonus: 8,
defenseBonus: 0,
hpBonus: 0,
condition: "worn",
icon: "🦾",
},
{
id: "pw_a_vk_la_r_01",
name: "[PATCHWORK] Volkov Strike Rig (L) - WORN",
description: "Left-side unit. The factory grip miscalibration is still there under the salvage marks. Volkov tolerances survive everything.",
rarity: "rare",
type: "augmentation",
slot: "left_arm",
attackBonus: 8,
defenseBonus: 0,
hpBonus: 0,
condition: "worn",
icon: "🦾",
},
{
id: "pw_a_kz_br_r_01",
name: "[PATCHWORK] Kizuna Shift-Manager Kernel - PRISTINE",
description: "Someone kept this one clean. The jailbreak is surgical - only the surveillance stripped, none of the precision. Cold start still bites.",
rarity: "rare",
type: "augmentation",
slot: "brain",
attackBonus: 5,
defenseBonus: 2,
hpBonus: 10,
condition: "pristine",
icon: "🧠",
},
{
id: "pw_a_cr_ey_r_01",
name: "[PATCHWORK] Crown Glare-Cut Optic - WORN",
description: "Polarised retinal filter from Crown survey stock. The warmth is still gone. Whoever wore this first stopped noticing. So will you.",
rarity: "rare",
type: "augmentation",
slot: "eyes",
attackBonus: 5,
defenseBonus: 0,
hpBonus: 4,
condition: "worn",
icon: "👁️",
},

// ----------
// PATCHWORK TYPE B - PLASTIC ISLAND ORIGIN
// Made on the gyre. No corporate heritage.
// Common/uncommon only. Never evasion.
// ----------

// ── COMMON ───────────────────────────────

{
id: "pw_b_arm_c_01",
name: "[PATCHWORK] Gyre-Cast Hook Arm (L)",
description: "Melted-down ocean plastic over a scrap-metal frame. The grip is a fixed hook, shaped by whoever had the mould. Functional. Heavy.",
rarity: "common",
type: "augmentation",
slot: "left_arm",
attackBonus: 2,
defenseBonus: 0,
hpBonus: 0,
condition: "worn",
icon: "🦾",
},
{
id: "pw_b_arm_c_02",
name: "[PATCHWORK] Gyre-Cast Hook Arm (R)",
description: "Right-side twin. The plastic took on a greenish hue in the curing - microalgae pigment in the gyre feedstock. Still solid.",
rarity: "common",
type: "augmentation",
slot: "right_arm",
attackBonus: 2,
defenseBonus: 0,
hpBonus: 0,
condition: "worn",
icon: "🦾",
},
{
id: "pw_b_leg_c_01",
name: "[PATCHWORK] Rope-Brace Leg (L)",
description: "Carbon-fibre strut salvaged from a turbine fin, lashed to the knee with braided net-cord. Holds if you don't push it.",
rarity: "common",
type: "augmentation",
slot: "left_leg",
attackBonus: 0,
defenseBonus: 1,
hpBonus: 3,
condition: "worn",
icon: "🦿",
},
{
id: "pw_b_leg_c_02",
name: "[PATCHWORK] Rope-Brace Leg (R)",
description: "Right-side rig. The cord was re-braided at some point - different colour, tighter weave. Someone cared enough to fix it properly.",
rarity: "common",
type: "augmentation",
slot: "right_leg",
attackBonus: 0,
defenseBonus: 1,
hpBonus: 3,
condition: "worn",
icon: "🦿",
},
{
id: "pw_b_lung_c_01",
name: "[PATCHWORK] Resin-Packed Lung Filter",
description: "Compressed plant-fibre and activated charcoal, sealed in repurposed turbine-housing resin. Does the job. Tastes like burning.",
rarity: "common",
type: "augmentation",
slot: "lungs",
attackBonus: 0,
defenseBonus: 0,
hpBonus: 7,
condition: "worn",
icon: "🫁",
},
{
id: "pw_b_ear_c_01",
name: "[PATCHWORK] Wax-Seal Ear Plugs",
description: "Subdermal insert hand-shaped from recycled polymer wax. Blocks industrial noise above a threshold that varies by temperature. Children on the rafts get these first.",
rarity: "common",
type: "augmentation",
slot: "ears",
attackBonus: 0,
defenseBonus: 1,
hpBonus: 2,
condition: "worn",
icon: "👂",
},
{
id: "pw_b_eye_c_01",
name: "[PATCHWORK] Smoked-Plastic Eye Shield",
description: "UV filter ground from salvaged tinted plastic. Not implanted - clamped to the orbital socket with a resin mount. Imprecise. Better than nothing on open water.",
rarity: "common",
type: "augmentation",
slot: "eyes",
attackBonus: 1,
defenseBonus: 0,
hpBonus: 2,
condition: "worn",
icon: "👁️",
},
{
id: "pw_b_misc_c_01",
name: "[PATCHWORK] Solar-Cell Spine Tap",
description: "A strip of salvaged photovoltaic cells wired into a spinal contact point. Trickle-charges whatever else you're running. The contact site itches in direct sun.",
rarity: "common",
type: "augmentation",
slot: "misc",
attackBonus: 0,
defenseBonus: 1,
hpBonus: 4,
condition: "worn",
icon: "⚙️",
},

// ── UNCOMMON ─────────────────────────────

{
id: "pw_b_arm_u_01",
name: "[PATCHWORK] Turbine-Claw Arm (L)",
description: "A wind-turbine maintenance claw, re-socketed into a shoulder mount by a raft guild mechanic. Grip force is extreme. Release is manual only.",
rarity: "uncommon",
type: "augmentation",
slot: "left_arm",
attackBonus: 5,
defenseBonus: 1,
hpBonus: 0,
condition: "worn",
icon: "🦾",
},
{
id: "pw_b_arm_u_02",
name: "[PATCHWORK] Turbine-Claw Arm (R)",
description: "Right-side claw. The guild that built these marks them with a stripe of orange paint. Every raft in the South China gyre knows what that stripe means.",
rarity: "uncommon",
type: "augmentation",
slot: "right_arm",
attackBonus: 5,
defenseBonus: 1,
hpBonus: 0,
condition: "worn",
icon: "🦾",
},
{
id: "pw_b_leg_u_01",
name: "[PATCHWORK] Hydro-Pod Leg (L)",
description: "A leg rig with a small water-wheel generator built into the calf. Generates trickle charge as you walk. The mechanism is audible. Everyone knows you're coming.",
rarity: "uncommon",
type: "augmentation",
slot: "left_leg",
attackBonus: 0,
defenseBonus: 2,
hpBonus: 8,
condition: "worn",
icon: "🦿",
},
{
id: "pw_b_leg_u_02",
name: "[PATCHWORK] Hydro-Pod Leg (R)",
description: "Right-side unit. The pair together can power a low-draw augment indefinitely at walking pace. Nobody walks slowly on a raft.",
rarity: "uncommon",
type: "augmentation",
slot: "right_leg",
attackBonus: 0,
defenseBonus: 2,
hpBonus: 8,
condition: "worn",
icon: "🦿",
},
{
id: "pw_b_lung_u_01",
name: "[PATCHWORK] Gyre-Kelp Lung Lining",
description: "Kelp-derived biofilm pressed into bronchial inserts. Filters microplastic particulates and some heavy metals. Grown on-raft. Replaced monthly. The taste never fully leaves.",
rarity: "uncommon",
type: "augmentation",
slot: "lungs",
attackBonus: 0,
defenseBonus: 1,
hpBonus: 18,
condition: "pristine",
icon: "🫁",
},
{
id: "pw_b_brain_u_01",
name: "[PATCHWORK] Drift-Guild Memory Chip",
description: "Hand-etched silicon on a repurposed industrial controller board. Stores navigational data and reaction patterns built up by the guild over decades. Warm on startup - already knows you.",
rarity: "uncommon",
type: "augmentation",
slot: "brain",
attackBonus: 2,
defenseBonus: 2,
hpBonus: 6,
condition: "pristine",
icon: "🧠",
},
{
id: "pw_b_nose_u_01",
name: "[PATCHWORK] Salt-Sense Nasal Wick",
description: "Porous polymer wick implanted in the nasal cavity. Tuned to detect salt concentration, chemical runoff and microplastic density in air. Built for survival on open water. Surprisingly effective in a fight.",
rarity: "uncommon",
type: "augmentation",
slot: "nose",
attackBonus: 0,
defenseBonus: 1,
hpBonus: 12,
condition: "pristine",
icon: "👃",
},

// ── STIM ITEMS ───────────────────────────────────────────────────────────────
// These are the 4 core combat consumables. consumableEffect drives the logic in useCombat.
// They exist alongside the older hpBonus consumables but are clearly labelled.
{
id: "stim_heat_flush",
name: "Heat Flush",
description: "Emergency thermal dump. Floods coolant through augment channels and bleeds excess heat through dermal vents. Smells like burning plastic. Works immediately.",
rarity: "uncommon",
type: "consumable" as const,
consumableEffect: "heat_flush" as const,
icon: "🧊",
},
{
id: "stim_bio",
name: "Bio-Stim",
description: "Adrenaline compound with coagulants and cellular repair accelerant. Standard-issue in Patchwork med-kits. The dose is technically an overdose. Nobody has complained yet.",
rarity: "uncommon",
type: "consumable" as const,
consumableEffect: "bio_stim" as const,
icon: "💉",
},
{
id: "stim_structural",
name: "Structural Patch",
description: "Rapid-set polymer resin for augment chassis repair. Injected directly into the structural layer. The setting process is not comfortable. The alternative is worse.",
rarity: "uncommon",
type: "consumable" as const,
consumableEffect: "structural_patch" as const,
icon: "🔩",
},
{
id: "stim_overclock",
name: "Overclock",
description: "Synthetic nerve accelerant. Doubles signal velocity for one attack cycle. The crash afterwards is significant. One use only - the compound breaks down instantly.",
rarity: "rare",
type: "consumable" as const,
consumableEffect: "overclock" as const,
icon: "⚡",
},
// -- Grafts and makers added for the Offshore Sector 7 market
{ id: "cbn_la_r_01", name: "[CBN] RIG Graft Arm", description: "Cartel muscle graft grown in a BASM unit off Sector 7. Hits through implant plating. The host body never stops rejecting it.", rarity: "rare", type: "augmentation", slot: "left_arm", icon: "🦾", attackBonus: 9, structuralAttackBonus: 4, passiveEffect: 'bypass_sdef' },
{ id: "cbn_ra_e_01", name: "[CBN] FAS Lash Graft", description: "Fast-twitch fibre lash from a cartel surgery barge. Feeds on the fight. Infection is a matter of when.", rarity: "epic", type: "augmentation", slot: "right_arm", icon: "🦾", attackBonus: 14, structuralAttackBonus: 6, passiveEffect: 'bypass_sdef' },
{ id: "tx_ra_u_02", name: "[TIANXIA] Dockhand Grip", description: "Labour-grade hand from the Pearl River container yards. Built to hold a crate all shift.", rarity: "uncommon", type: "augmentation", slot: "right_arm", icon: "🦾", attackBonus: 4, defenseBonus: 3, hpBonus: 6 },
{ id: "cr_la_r_01", name: "[CROWN] Concierge Arm", description: "Clinic-finished limb for executives who still like to throw the first punch. Runs cool.", rarity: "rare", type: "augmentation", slot: "left_arm", icon: "🦾", attackBonus: 7, defenseBonus: 5, hpBonus: 8 },
{ id: "kz_ra_l_01", name: "[KIZUNA] Mediator Hand", description: "MIL-signed precision limb. Every motion is logged and approved before it lands.", rarity: "legendary", type: "augmentation", slot: "right_arm", icon: "🦾", attackBonus: 18, defenseBonus: 6, structuralAttackBonus: 6, passiveEffect: 'kizuna_coldstart' },
{ id: "io_la_u_01", name: "[IOA] Limiter-Free Forearm", description: "Counterfeit forearm with the safety firmware stripped on a grey lane. It will tear your shoulder eventually.", rarity: "uncommon", type: "augmentation", slot: "left_arm", icon: "🦾", attackBonus: 7, structuralAttackBonus: 2 },
{ id: "hx_la_e_01", name: "[HELIX] Bulwark Housing Arm", description: "Helix continuity hardware: a limb built to take hits for the platform. Helix makes no weapons.", rarity: "epic", type: "augmentation", slot: "left_arm", icon: "🛡️", defenseBonus: 12, structuralDefenseBonus: 8, hpBonus: 12 },
{ id: "ps_ra_c_01", name: "[PARSU] Substrate Cudgel Arm", description: "Raw composite forearm poured in a PARSU mould. Heavy and dumb.", rarity: "common", type: "augmentation", slot: "right_arm", icon: "🦾", attackBonus: 3, structuralDefenseBonus: 1 },
{ id: "tx_ll_c_02", name: "[TIANXIA] Loader Leg", description: "Workforce leg rated for twelve-hour standing shifts.", rarity: "common", type: "augmentation", slot: "left_leg", icon: "🦿", attackBonus: 1, defenseBonus: 2, hpBonus: 4 },
{ id: "vk_rl_r_01", name: "[VOLKOV] Breach Strider", description: "Operator leg tuned for door breaching. The knee is louder than the gun.", rarity: "rare", type: "augmentation", slot: "right_leg", icon: "🦿", attackBonus: 8, defenseBonus: 3, hpBonus: 4 },
{ id: "cbn_ll_e_01", name: "[CBN] SCAR Spring Graft", description: "Cartel tendon graft that stores and dumps energy. The scar tissue keeps spreading.", rarity: "epic", type: "augmentation", slot: "left_leg", icon: "🦿", attackBonus: 10, evasionBonus: 3, passiveEffect: 'bypass_sdef' },
{ id: "kz_rl_u_01", name: "[KIZUNA] Gyro-Stable Shin", description: "Balance-stabilised shin for MIL couriers.", rarity: "uncommon", type: "augmentation", slot: "right_leg", icon: "🦿", attackBonus: 3, defenseBonus: 2, evasionBonus: 1 },
{ id: "cr_ll_r_01", name: "[CROWN] Poise Leg", description: "Luxury clinic leg. Graceful, quiet, and kind to the hip.", rarity: "rare", type: "augmentation", slot: "left_leg", icon: "🦿", defenseBonus: 5, hpBonus: 12, evasionBonus: 1 },
{ id: "vk_ll_l_01", name: "[VOLKOV] Operator Drive Leg", description: "Full Volkov operator suite leg. Closes distance like a thrown anchor.", rarity: "legendary", type: "augmentation", slot: "left_leg", icon: "🦿", attackBonus: 20, defenseBonus: 8, hpBonus: 8 },
{ id: "kz_ey_e_01", name: "[KIZUNA] Signed Optic", description: "MIL-signed targeting optic. Locks never drift.", rarity: "epic", type: "augmentation", slot: "eyes", icon: "👁️", attackBonus: 12, defenseBonus: 4, structuralAttackBonus: 4, passiveEffect: 'kizuna_coldstart' },
{ id: "vk_ey_r_01", name: "[VOLKOV] Operator Overlay", description: "Combat overlay ripped from a Volkov operator helmet and wired straight into the optic nerve.", rarity: "rare", type: "augmentation", slot: "eyes", icon: "👁️", attackBonus: 10, structuralAttackBonus: 3 },
{ id: "io_ey_u_01", name: "[IOA] Cracked HUD", description: "Grey-lane retinal firmware. Fast aim, frequent migraines.", rarity: "uncommon", type: "augmentation", slot: "eyes", icon: "👁️", attackBonus: 6, structuralAttackBonus: 1 },
{ id: "cbn_ms_r_01", name: "[CBN] Marrow Graft", description: "Cartel spinal marrow graft. Your hits find the seams in implant plating. Your body hates it.", rarity: "rare", type: "augmentation", slot: "misc", icon: "🦴", attackBonus: 8, structuralAttackBonus: 5, passiveEffect: 'bypass_sdef' },
{ id: "ps_lu_u_01", name: "[PARSU] Composite Lung Mesh", description: "Substrate mesh liner. Stiff, but it keeps the fumes out.", rarity: "uncommon", type: "augmentation", slot: "lungs", icon: "🫁", defenseBonus: 4, hpBonus: 12, structuralDefenseBonus: 2 },
{ id: "cr_br_e_01", name: "[CROWN] Restorative Kernel", description: "Crown clinic kernel that keeps the body healing between fights.", rarity: "epic", type: "augmentation", slot: "brain", icon: "🧠", defenseBonus: 8, hpBonus: 36 },
{ id: "hx_nz_r_01", name: "[HELIX] Filter Septum", description: "Helix survival filter. Leachate fumes stop being a problem.", rarity: "rare", type: "augmentation", slot: "nose", icon: "👃", defenseBonus: 6, hpBonus: 16, structuralDefenseBonus: 3 },
{ id: "ps_ms_e_01", name: "[PARSU] Substrate Spine", description: "A spine cast in raw composite. Almost nothing breaks it.", rarity: "epic", type: "augmentation", slot: "misc", icon: "🦴", defenseBonus: 10, structuralDefenseBonus: 10, hpBonus: 8 },
{ id: "io_br_r_01", name: "[IOA] Grey Firmware Kernel", description: "Unlicensed brain firmware. Faster thinking, no safety rails.", rarity: "rare", type: "augmentation", slot: "brain", icon: "🧠", attackBonus: 10, structuralAttackBonus: 4 },
];

/** All items, with implants brought into the power band for their rarity. */
export const ITEMS_2059: Item[] = BASE_ITEMS.map(normaliseItem);
