import { Weapon } from './types';

// ── WEAPONS 2059 ──────────────────────────────────────────────────────────────
// 4 manufacturers x 3 weapon types x 2 tiers = 24 weapons
//
// Volkov:  precision violence. High P-ATK + S-ATK. Structural-shredding at higher tiers.
// Tianxia: workforce-grade. Cheap, UNRELIABLE, high raw damage to compensate.
// CBN:     bio-targeted. physicalRatio 1.0, bypassStructuralDefense. Pure meat damage.
// IOA:     dock suppression. Structural-heavy physicalRatio. Shreds cybernetics.
//
// Tier 2 ids = tier 1 id + '_mk2'
// Sell price = ~40% of buy price (rounded to nearest 10)

export const WEAPONS_2059: Weapon[] = [

// ── VOLKOV ────────────────────────────────────────────────────────────────────

{
id: 'vk_w_pistol_t1',
name: '[VOLKOV] Operator Sidearm',
description: 'Standard-issue Volkov precision sidearm. The engineering note on the grip reads: one round, one result. Volkov considers repeating yourself a design failure.',
manufacturer: 'volkov',
weaponType: 'pistol',
tier: 1,
price: 180,
sellPrice: 70,
upgradePrice: 220,
icon: '🔫',
combatAction: {
type: 'attack',
name: 'Operator Sidearm',
description: 'Precision shot. Structural-capable.',
damage: 20,
heatGenerated: 18,
accuracy: 'precise',
physicalRatio: 0.60,
},
},
{
id: 'vk_w_pistol_t2',
name: '[VOLKOV] Operator Sidearm MK-2',
description: 'Breach-modified frame. The barrel is rated for rounds it was not originally designed to fire. Volkov considers this an upgrade.',
manufacturer: 'volkov',
weaponType: 'pistol',
tier: 2,
upgradeOfId: 'vk_w_pistol_t1',
price: 400,
sellPrice: 160,
icon: '🔫',
combatAction: {
type: 'attack',
name: 'Operator Sidearm MK-2',
description: 'Precision shot. Higher structural penetration.',
damage: 28,
heatGenerated: 18,
accuracy: 'precise',
physicalRatio: 0.50,
},
},

{
id: 'vk_w_revolver_t1',
name: '[VOLKOV] Chamber Load',
description: 'Six-round combat revolver. Each chamber is individually toleranced. Slower than semi-auto. Volkov argues that speed is for people who miss.',
manufacturer: 'volkov',
weaponType: 'revolver',
tier: 1,
price: 220,
sellPrice: 90,
upgradePrice: 260,
icon: '🔫',
combatAction: {
type: 'attack',
name: 'Chamber Load',
description: 'High-damage single shot. Structural penetration.',
damage: 30,
heatGenerated: 28,
accuracy: 'precise',
physicalRatio: 0.55,
},
},
{
id: 'vk_w_revolver_t2',
name: '[VOLKOV] Chamber Load (Breach)',
description: 'Cylinder enlarged, rounds recalibrated. The weapon now fires rounds designed for a vehicle mount. Volkov classifies this as personal use.',
manufacturer: 'volkov',
weaponType: 'revolver',
tier: 2,
upgradeOfId: 'vk_w_revolver_t1',
price: 480,
sellPrice: 190,
icon: '🔫',
combatAction: {
type: 'attack',
name: 'Chamber Load (Breach)',
description: 'Extreme damage. Heavy structural shred.',
damage: 42,
heatGenerated: 28,
accuracy: 'precise',
physicalRatio: 0.45,
},
},

{
id: 'vk_w_shotgun_t1',
name: '[VOLKOV] Frame Breach',
description: 'Close-quarters structural disassembly. Designed for breaching augmented targets in confined spaces. The spread pattern is not an accident.',
manufacturer: 'volkov',
weaponType: 'shotgun',
tier: 1,
price: 250,
sellPrice: 100,
upgradePrice: 300,
icon: '🔫',
combatAction: {
type: 'attack',
name: 'Frame Breach',
description: 'Close-range. Heavy structural damage.',
damage: 36,
heatGenerated: 32,
accuracy: 'unreliable',
physicalRatio: 0.40,
rangeOptimal: 'close',
},
},
{
id: 'vk_w_shotgun_t2',
name: '[VOLKOV] Frame Breach (Stripped)',
description: 'Choke removed. Recoil compensator removed. What remains is the part that does the work.',
manufacturer: 'volkov',
weaponType: 'shotgun',
tier: 2,
upgradeOfId: 'vk_w_shotgun_t1',
price: 550,
sellPrice: 220,
icon: '🔫',
combatAction: {
type: 'attack',
name: 'Frame Breach (Stripped)',
description: 'Extreme structural shred at close range.',
damage: 50,
heatGenerated: 32,
accuracy: 'unreliable',
physicalRatio: 0.35,
rangeOptimal: 'close',
},
},

// ── TIANXIA ───────────────────────────────────────────────────────────────────

{
id: 'tx_w_pistol_t1',
name: '[TIANXIA] Workforce Sidearm',
description: 'Standard-issue for Tianxia compliance personnel. Produced in volumes that make quality control aspirational. They ship anyway.',
manufacturer: 'tianxia',
weaponType: 'pistol',
tier: 1,
price: 120,
sellPrice: 50,
upgradePrice: 150,
icon: '🔫',
combatAction: {
type: 'attack',
name: 'Workforce Sidearm',
description: 'Cheap. Unreliable. High raw damage.',
damage: 22,
heatGenerated: 16,
accuracy: 'unreliable',
physicalRatio: 0.70,
},
},
{
id: 'tx_w_pistol_t2',
name: '[TIANXIA] Workforce Sidearm (V2)',
description: 'Second production batch. The tolerances are slightly tighter. Tianxia considers this a premium product.',
manufacturer: 'tianxia',
weaponType: 'pistol',
tier: 2,
upgradeOfId: 'tx_w_pistol_t1',
price: 270,
sellPrice: 110,
icon: '🔫',
combatAction: {
type: 'attack',
name: 'Workforce Sidearm (V2)',
description: 'Improved reliability. More damage.',
damage: 30,
heatGenerated: 16,
accuracy: 'variable',
physicalRatio: 0.70,
},
},

{
id: 'tx_w_revolver_t1',
name: '[TIANXIA] Compliance Revolver',
description: 'Issued to workforce supervisors. The weight is intentional. So is the noise.',
manufacturer: 'tianxia',
weaponType: 'revolver',
tier: 1,
price: 150,
sellPrice: 60,
upgradePrice: 190,
icon: '🔫',
combatAction: {
type: 'attack',
name: 'Compliance Revolver',
description: 'High damage. Unreliable under pressure.',
damage: 32,
heatGenerated: 26,
accuracy: 'unreliable',
physicalRatio: 0.65,
},
},
{
id: 'tx_w_revolver_t2',
name: '[TIANXIA] Compliance Revolver (Reinforced)',
description: 'Frame reinforced after field complaints. The complaints were about reliability. The reinforcement addresses the frame.',
manufacturer: 'tianxia',
weaponType: 'revolver',
tier: 2,
upgradeOfId: 'tx_w_revolver_t1',
price: 340,
sellPrice: 140,
icon: '🔫',
combatAction: {
type: 'attack',
name: 'Compliance Revolver (Reinforced)',
description: 'Variable reliability. High damage.',
damage: 44,
heatGenerated: 26,
accuracy: 'variable',
physicalRatio: 0.65,
},
},

{
id: 'tx_w_shotgun_t1',
name: '[TIANXIA] Crowd Management Unit',
description: 'Not a weapon, officially. A crowd management tool. The distinction is in the paperwork.',
manufacturer: 'tianxia',
weaponType: 'shotgun',
tier: 1,
price: 170,
sellPrice: 70,
upgradePrice: 210,
icon: '🔫',
combatAction: {
type: 'attack',
name: 'Crowd Management Unit',
description: 'Scatter fire. Unreliable but punishing.',
damage: 38,
heatGenerated: 30,
accuracy: 'unreliable',
physicalRatio: 0.75,
rangeOptimal: 'close',
},
},
{
id: 'tx_w_shotgun_t2',
name: '[TIANXIA] Crowd Management Unit (V2)',
description: 'Updated to meet post-incident requirements. Tianxia did not specify which incident.',
manufacturer: 'tianxia',
weaponType: 'shotgun',
tier: 2,
upgradeOfId: 'tx_w_shotgun_t1',
price: 380,
sellPrice: 150,
icon: '🔫',
combatAction: {
type: 'attack',
name: 'Crowd Management Unit (V2)',
description: 'Upgraded scatter. More damage.',
damage: 52,
heatGenerated: 30,
accuracy: 'unreliable',
physicalRatio: 0.75,
rangeOptimal: 'close',
},
},

// ── CBN ───────────────────────────────────────────────────────────────────────
// physicalRatio: 1.0 + bypassStructuralDefense: true
// Attacks go straight for the biology. Cybernetics offer no protection.

{
id: 'cbn_w_pistol_t1',
name: '[CBN] Dermal Injector',
description: 'Fires a pressurised bio-agent capsule. Bypasses surface armour entirely. Whatever you have grafted onto yourself, the biology underneath is still soft.',
manufacturer: 'cbn',
weaponType: 'pistol',
tier: 1,
price: 200,
sellPrice: 80,
upgradePrice: 240,
icon: '🔫',
combatAction: {
type: 'attack',
name: 'Dermal Injector',
description: 'Pure bio damage. Bypasses S-DEF entirely.',
damage: 18,
heatGenerated: 14,
accuracy: 'variable',
physicalRatio: 1.0,
bypassStructuralDefense: true,
},
},
{
id: 'cbn_w_pistol_t2',
name: '[CBN] Dermal Injector (Concentrated)',
description: 'Higher-concentration payload. The capsule dissolves faster. CBN considers the speed of effect a feature.',
manufacturer: 'cbn',
weaponType: 'pistol',
tier: 2,
upgradeOfId: 'cbn_w_pistol_t1',
price: 440,
sellPrice: 180,
icon: '🔫',
combatAction: {
type: 'attack',
name: 'Dermal Injector (Concentrated)',
description: 'Pure bio damage. Bypasses S-DEF entirely.',
damage: 26,
heatGenerated: 14,
accuracy: 'variable',
physicalRatio: 1.0,
bypassStructuralDefense: true,
},
},

{
id: 'cbn_w_revolver_t1',
name: '[CBN] Vascular Punch',
description: 'Slow-cycling bio-agent revolver. Each round is a different formulation. CBN does not disclose which is which.',
manufacturer: 'cbn',
weaponType: 'revolver',
tier: 1,
price: 240,
sellPrice: 100,
upgradePrice: 290,
icon: '🔫',
combatAction: {
type: 'attack',
name: 'Vascular Punch',
description: 'Heavy bio hit. Full S-DEF bypass.',
damage: 28,
heatGenerated: 24,
accuracy: 'precise',
physicalRatio: 1.0,
bypassStructuralDefense: true,
},
},
{
id: 'cbn_w_revolver_t2',
name: '[CBN] Vascular Punch (Black Grade)',
description: 'Black-access formulation. Not available through official CBN channels. Officially.',
manufacturer: 'cbn',
weaponType: 'revolver',
tier: 2,
upgradeOfId: 'cbn_w_revolver_t1',
price: 530,
sellPrice: 210,
icon: '🔫',
combatAction: {
type: 'attack',
name: 'Vascular Punch (Black Grade)',
description: 'Extreme bio damage. Full S-DEF bypass.',
damage: 40,
heatGenerated: 24,
accuracy: 'precise',
physicalRatio: 1.0,
bypassStructuralDefense: true,
},
},

{
id: 'cbn_w_shotgun_t1',
name: '[CBN] Aerosol Dispersal Frame',
description: 'Aerosolised bio-agent delivery. Wide dispersal pattern. The agent does not distinguish between targets. CBN advises maintaining safe personal distance.',
manufacturer: 'cbn',
weaponType: 'shotgun',
tier: 1,
price: 260,
sellPrice: 100,
upgradePrice: 320,
icon: '🔫',
combatAction: {
type: 'attack',
name: 'Aerosol Dispersal Frame',
description: 'Bio burst. Bypasses S-DEF. Short range.',
damage: 32,
heatGenerated: 28,
accuracy: 'unreliable',
physicalRatio: 1.0,
bypassStructuralDefense: true,
rangeOptimal: 'close',
},
},
{
id: 'cbn_w_shotgun_t2',
name: '[CBN] Aerosol Dispersal Frame (Saturated)',
description: 'Higher saturation payload. The dispersal cloud is thicker. CBN does not recommend breathing near the impact zone.',
manufacturer: 'cbn',
weaponType: 'shotgun',
tier: 2,
upgradeOfId: 'cbn_w_shotgun_t1',
price: 580,
sellPrice: 230,
icon: '🔫',
combatAction: {
type: 'attack',
name: 'Aerosol Dispersal Frame (Saturated)',
description: 'Heavy bio burst. Bypasses S-DEF. Short range.',
damage: 46,
heatGenerated: 28,
accuracy: 'unreliable',
physicalRatio: 1.0,
bypassStructuralDefense: true,
rangeOptimal: 'close',
},
},

// ── IOA ───────────────────────────────────────────────────────────────────────
// Structural-heavy. Low physicalRatio. Shreds cybernetics and grafted chassis.

{
id: 'ioa_w_pistol_t1',
name: '[IOA] Dock Security Sidearm',
description: 'Standard issue for IOA platform security. Designed for interdicting augmented boarders. The structural disruption pattern was a deliberate specification.',
manufacturer: 'ioa',
weaponType: 'pistol',
tier: 1,
price: 160,
sellPrice: 60,
upgradePrice: 200,
icon: '🔫',
combatAction: {
type: 'attack',
name: 'Dock Security Sidearm',
description: 'Structural-heavy. Targets cybernetics.',
damage: 20,
heatGenerated: 16,
accuracy: 'variable',
physicalRatio: 0.35,
},
},
{
id: 'ioa_w_pistol_t2',
name: '[IOA] Dock Security Sidearm (Hardened)',
description: 'Second-generation frame with reinforced emitter coil. IOA found the first generation performed well enough that they upgraded it anyway.',
manufacturer: 'ioa',
weaponType: 'pistol',
tier: 2,
upgradeOfId: 'ioa_w_pistol_t1',
price: 360,
sellPrice: 140,
icon: '🔫',
combatAction: {
type: 'attack',
name: 'Dock Security Sidearm (Hardened)',
description: 'Heavier structural disruption.',
damage: 28,
heatGenerated: 16,
accuracy: 'variable',
physicalRatio: 0.30,
},
},

{
id: 'ioa_w_revolver_t1',
name: '[IOA] Platform Enforcer',
description: 'Slow-fire heavy sidearm. Each round carries a structural disruption charge. Primarily deployed against salvage crews operating without clearance.',
manufacturer: 'ioa',
weaponType: 'revolver',
tier: 1,
price: 200,
sellPrice: 80,
upgradePrice: 240,
icon: '🔫',
combatAction: {
type: 'attack',
name: 'Platform Enforcer',
description: 'High structural damage. Variable accuracy.',
damage: 30,
heatGenerated: 26,
accuracy: 'variable',
physicalRatio: 0.30,
},
},
{
id: 'ioa_w_revolver_t2',
name: '[IOA] Platform Enforcer (Heavy Charge)',
description: 'Increased charge density. The rounds are heavier. The cycling time is longer. IOA determined this was acceptable.',
manufacturer: 'ioa',
weaponType: 'revolver',
tier: 2,
upgradeOfId: 'ioa_w_revolver_t1',
price: 440,
sellPrice: 180,
icon: '🔫',
combatAction: {
type: 'attack',
name: 'Platform Enforcer (Heavy Charge)',
description: 'Extreme structural damage.',
damage: 42,
heatGenerated: 26,
accuracy: 'variable',
physicalRatio: 0.25,
},
},

{
id: 'ioa_w_shotgun_t1',
name: '[IOA] Boarding Suppressor',
description: 'Wide-pattern structural disruption. Deployed for close-quarters interdiction of augmented boarding parties. IOA does not consider the etymology of the word "suppressor" ironic.',
manufacturer: 'ioa',
weaponType: 'shotgun',
tier: 1,
price: 230,
sellPrice: 90,
upgradePrice: 280,
icon: '🔫',
combatAction: {
type: 'attack',
name: 'Boarding Suppressor',
description: 'Heavy structural scatter at close range.',
damage: 38,
heatGenerated: 30,
accuracy: 'unreliable',
physicalRatio: 0.25,
rangeOptimal: 'close',
},
},
{
id: 'ioa_w_shotgun_t2',
name: '[IOA] Boarding Suppressor (Dense Charge)',
description: 'Denser charge pattern. Field-modified by IOA platform crews after encountering targets with reinforced structural hardware.',
manufacturer: 'ioa',
weaponType: 'shotgun',
tier: 2,
upgradeOfId: 'ioa_w_shotgun_t1',
price: 510,
sellPrice: 200,
icon: '🔫',
combatAction: {
type: 'attack',
name: 'Boarding Suppressor (Dense Charge)',
description: 'Extreme structural scatter. Close range.',
damage: 54,
heatGenerated: 30,
accuracy: 'unreliable',
physicalRatio: 0.20,
rangeOptimal: 'close',
},
},

];

// Helper: get all tier-1 weapons (available to buy fresh)
export const TIER1_WEAPONS = WEAPONS_2059.filter(w => w.tier === 1);

// Helper: get tier-2 upgrade for a given tier-1 weapon id
export function getUpgrade(tier1Id: string): Weapon | undefined {
return WEAPONS_2059.find(w => w.upgradeOfId === tier1Id);
}